# Generated by Django 4.2 on 2026-04-14 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=500)),
                ('chemin_fichier', models.TextField()),
                ('nom_fichier', models.CharField(max_length=255)),
                ('hash_sha256', models.CharField(max_length=64, unique=True)),
                ('taille_bytes', models.BigIntegerField(null=True)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('traitement', 'Traitement'), ('complet', 'Complet'), ('echoue', 'Echoue')], default='pending', max_length=20)),
                ('full_text', models.TextField(blank=True)),
                ('date_indexation', models.DateTimeField(auto_now_add=True)),
                ('upload_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_page', models.IntegerField()),
                ('texte', models.TextField()),
                ('hash_page', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='docs.document')),
            ],
        ),
        migrations.CreateModel(
            name='IndexMot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(db_index=True, max_length=100)),
                ('occurences', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.document')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.page')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adresse', models.CharField(default='personnelle', max_length=20)),
                ('reference_dossier', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(default='actif', max_length=50)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
    ]
