# Generated by Django 4.2 on 2026-04-18 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_client_est_actif_historicalutilisateur_and_more'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='date_cloture',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='type_adresse',
        ),
        migrations.AlterField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('traitement', 'Traitement'), ('complet', 'Complet'), ('echoue', 'Echoue')], default='en attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client'),
        ),
        migrations.CreateModel(
            name='HistoricalDossier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reference_dossier', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(default='actif', max_length=50)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dossier',
                'verbose_name_plural': 'historical dossiers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
