# Generated by Django 4.2 on 2026-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_remove_dossier_date_cloture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date_indexation',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
