# Generated by Django 4.2 on 2026-04-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_historicalpersonnemorale_historicalpersonnephysique_and_more'),
        ('docs', '0003_rename_date_indexation_document_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Dossier', 'verbose_name_plural': 'Dossiers'},
        ),
        migrations.AlterModelOptions(
            name='historicaldossier',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Dossier', 'verbose_name_plural': 'historical Dossiers'},
        ),
        migrations.AddField(
            model_name='dossier',
            name='chemin_dossier',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_ouverture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldossier',
            name='chemin_dossier',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='historicaldossier',
            name='date_ouverture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('cloture', 'Clôturé'), ('archive', 'Archivé'), ('suspendu', 'Suspendu')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldossier',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('cloture', 'Clôturé'), ('archive', 'Archivé'), ('suspendu', 'Suspendu')], default='actif', max_length=20),
        ),
    ]
