# Generated by Django 4.2 on 2026-04-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_est_actif_historicalutilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
    ]
