# Generated by Django 4.2 on 2026-04-24 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_auditlog_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersonneMorale',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=255)),
                ('sigle', models.CharField(blank=True, max_length=50)),
                ('type_societe', models.CharField(blank=True, choices=[('SARL', 'SARL'), ('SA', 'Société Anonyme'), ('SAS', 'SAS'), ('SNC', 'SNC'), ('SCI', 'SCI'), ('Association', 'Association'), ('Autre', 'Autre')], max_length=50)),
                ('numero_rc', models.CharField(blank=True, max_length=100, verbose_name='Numéro Registre de Commerce')),
                ('numero_patente', models.CharField(blank=True, max_length=100)),
                ('identifiant_fiscal', models.CharField(blank=True, max_length=100)),
                ('numero_cnss', models.CharField(blank=True, max_length=100)),
                ('ice', models.CharField(blank=True, max_length=100, verbose_name="ICE (Identifiant Commun de l'Entreprise)")),
                ('representant_nom', models.CharField(blank=True, max_length=100)),
                ('representant_prenom', models.CharField(blank=True, max_length=100)),
                ('representant_fonction', models.CharField(blank=True, max_length=100)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('devise', models.CharField(default='MAD', max_length=3)),
                ('effectif', models.IntegerField(blank=True, null=True)),
                ('date_creation_societe', models.DateField(blank=True, null=True)),
                ('date_immatriculation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical personne morale',
                'verbose_name_plural': 'historical personne morales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPersonnePhysique',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_identite', models.CharField(blank=True, max_length=50)),
                ('numero_identite', models.CharField(db_index=True, max_length=50)),
                ('nationalite', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('situation_familiale', models.CharField(blank=True, max_length=50)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical personne physique',
                'verbose_name_plural': 'historical personne physiques',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PersonneMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=255)),
                ('sigle', models.CharField(blank=True, max_length=50)),
                ('type_societe', models.CharField(blank=True, choices=[('SARL', 'SARL'), ('SA', 'Société Anonyme'), ('SAS', 'SAS'), ('SNC', 'SNC'), ('SCI', 'SCI'), ('Association', 'Association'), ('Autre', 'Autre')], max_length=50)),
                ('numero_rc', models.CharField(blank=True, max_length=100, verbose_name='Numéro Registre de Commerce')),
                ('numero_patente', models.CharField(blank=True, max_length=100)),
                ('identifiant_fiscal', models.CharField(blank=True, max_length=100)),
                ('numero_cnss', models.CharField(blank=True, max_length=100)),
                ('ice', models.CharField(blank=True, max_length=100, verbose_name="ICE (Identifiant Commun de l'Entreprise)")),
                ('representant_nom', models.CharField(blank=True, max_length=100)),
                ('representant_prenom', models.CharField(blank=True, max_length=100)),
                ('representant_fonction', models.CharField(blank=True, max_length=100)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('devise', models.CharField(default='MAD', max_length=3)),
                ('effectif', models.IntegerField(blank=True, null=True)),
                ('date_creation_societe', models.DateField(blank=True, null=True)),
                ('date_immatriculation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_identite', models.CharField(blank=True, max_length=50)),
                ('numero_identite', models.CharField(max_length=50, unique=True)),
                ('nationalite', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('situation_familiale', models.CharField(blank=True, max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='profession',
            new_name='ville',
        ),
        migrations.RenameField(
            model_name='historicalclient',
            old_name='profession',
            new_name='ville',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='numero_identite',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type_identite',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='numero_identite',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='type_identite',
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='pays',
            field=models.CharField(default='Maroc', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('physique', 'Personne physique'), ('morale', 'Personne morale')], default='physique', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='pays',
            field=models.CharField(default='Maroc', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='type_client',
            field=models.CharField(choices=[('physique', 'Personne physique'), ('morale', 'Personne morale')], default='physique', max_length=10),
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
        migrations.AddField(
            model_name='client',
            name='personne_morale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.personnemorale'),
        ),
        migrations.AddField(
            model_name='client',
            name='personne_physique',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.personnephysique'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='personne_morale',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.personnemorale'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='personne_physique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.personnephysique'),
        ),
    ]
